import {NextResponse} from "next/server";

export async function GET() {
	return NextResponse.json({
		data: dataConveyance
	})
}

export const dataConveyance = [
	{
		id: 1,
		name: 'BR80365 (422, ON, CA)',
		type: 'Van',
		conveyanceNumber: '422',
		primaryPlate: 'BR80365',
		vin: '1FTBR3U85MKA87274',
		country: 'Canada',
		state: 'Ontario',
		primaryPlateState: '',
		make: '',
		modelYear: '',
		style: '',
		secondaryPlate: '',
		secondaryCountry: '',
		secondaryState: '',
		insurer: '',
		policyNumber: '',
		policyIssueDate: '',
		coverageAmount: ''
	}, {
		id: 2,
		name: 'BR80365 (422, ON, CA)',
		type: 'Van',
		conveyanceNumber: '422',
		primaryPlate: 'BR80365',
		vin: '1FTBR3U85MKA87274',
		country: 'Canada',
		state: 'Ontario',
		primaryPlateState: '',
		make: '',
		modelYear: '',
		style: '',
		secondaryPlate: '',
		secondaryCountry: '',
		secondaryState: '',
		insurer: '',
		policyNumber: '',
		policyIssueDate: '',
		coverageAmount: ''
	}, {
		id: 3,
		name: 'CXNC969 (401, ON, CA)',
		type: 'Van',
		conveyanceNumber: '422',
		primaryPlate: 'BR80365',
		vin: '1FTBR3U85MKA87274',
		country: 'Canada',
		state: 'Ontario',
		primaryPlateState: '',
		make: '',
		modelYear: '',
		style: '',
		secondaryPlate: '',
		secondaryCountry: '',
		secondaryState: '',
		insurer: '',
		policyNumber: '',
		policyIssueDate: '',
		coverageAmount: ''
	}, {
		id: 4,
		name: 'BT62934 (423, ON, CA)',
		type: 'Van',
		conveyanceNumber: '422',
		primaryPlate: 'BR80365',
		vin: '1FTBR3U85MKA87274',
		country: 'Canada',
		state: 'Ontario',
		primaryPlateState: '',
		make: '',
		modelYear: '',
		style: '',
		secondaryPlate: '',
		secondaryCountry: '',
		secondaryState: '',
		insurer: '',
		policyNumber: '',
		policyIssueDate: '',
		coverageAmount: ''
	}, {
		id: 5,
		name: 'BK99018 (424, ON, CA)',
		type: 'Van',
		conveyanceNumber: '422',
		primaryPlate: 'BR80365',
		vin: '1FTBR3U85MKA87274',
		country: 'Canada',
		state: 'Ontario',
		primaryPlateState: '',
		make: '',
		modelYear: '',
		style: '',
		secondaryPlate: '',
		secondaryCountry: '',
		secondaryState: '',
		insurer: '',
		policyNumber: '',
		policyIssueDate: '',
		coverageAmount: ''
	}, {
		id: 6,
		name: 'AX76174 (402, ON, CA)',
		type: 'Van',
		conveyanceNumber: '422',
		primaryPlate: 'BR80365',
		vin: '1FTBR3U85MKA87274',
		country: 'Canada',
		state: 'Ontario',
		primaryPlateState: '',
		make: '',
		modelYear: '',
		style: '',
		secondaryPlate: '',
		secondaryCountry: '',
		secondaryState: '',
		insurer: '',
		policyNumber: '',
		policyIssueDate: '',
		coverageAmount: ''
	}, {
		id: 7,
		name: 'BP75492 (425, ON, CA)',
		type: 'Van',
		conveyanceNumber: '422',
		primaryPlate: 'BR80365',
		vin: '1FTBR3U85MKA87274',
		country: 'Canada',
		state: 'Ontario',
		primaryPlateState: '',
		make: '',
		modelYear: '',
		style: '',
		secondaryPlate: '',
		secondaryCountry: '',
		secondaryState: '',
		insurer: '',
		policyNumber: '',
		policyIssueDate: '',
		coverageAmount: ''
	}, {
		id: 8,
		name: 'CXNC969 (104, ON, CA)',
		type: 'Van',
		conveyanceNumber: '422',
		primaryPlate: 'BR80365',
		vin: '1FTBR3U85MKA87274',
		country: 'Canada',
		state: 'Ontario',
		primaryPlateState: '',
		make: '',
		modelYear: '',
		style: '',
		secondaryPlate: '',
		secondaryCountry: '',
		secondaryState: '',
		insurer: '',
		policyNumber: '',
		policyIssueDate: '',
		coverageAmount: ''
	}
]







