export const uomSelect = [
	{value: 'Bag', label: 'Bag'},
	{value: 'Bale', label: 'Bale'},
	{value: 'Barrel', label: 'Barrel'},
	{value: 'Basket or hamper', label: 'Basket or hamper'},
	{value: 'Bin', label: 'Basket or hamperBin'},
	{value: 'Bing Chest', label: 'Bing Chest'},
	{value: 'BoX', label: 'BoX'},
	{value: 'Bucket', label: 'Bucket'},
	{value: 'Bundle', label: 'Bundle'},
	{value: 'Can', label: 'Can'},
	{value: 'Can Case', label: 'Can Case'},
	{value: 'Carboy', label: 'Carboy'},
	{value: 'Carrier', label: 'Carrier'},
	{value: 'Carton', label: 'Carton'},
	{value: 'Cask', label: 'Cask'},
	{value: 'Chest', label: 'Chest'},
	{value: 'Coil', label: 'Coil'},
	{value: 'Containers of Bulk Cargo', label: 'Containers of Bulk Cargo'},
	{value: 'Core', label: 'Core'},
	{value: 'Crate', label: 'Crate'},
	{value: 'Cylinder', label: 'Cylinder'},
	{value: 'Dozen', label: 'Dozen'},
	{value: 'Drum', label: 'DozenDrum'},
	{value: 'Dry Bulk', label: 'Dry Bulk'},
	{value: 'Feet', label: 'Feet'},
	{value: 'Heads of Beef', label: 'Heads of Beef'},
	{value: 'Keg', label: 'Keg'},
	{value: 'Lift Van', label: 'Lift Van'},
	{value: 'Liquid Bulk', label: 'Liquid Bulk'},
	{value: 'Liter', label: 'Liter'},
	{value: 'Log', label: 'Log'},
	{value: 'Lug', label: 'Lug'},
	{value: 'Meter', label: 'Meter'},
	{value: 'Package', label: 'Package'},
	{value: 'Pail', label: 'Pail'},
	{value: 'Pieces', label: 'Pieces'},
	{value: 'Private Vehicle', label: 'Private Vehicle'},
	{value: 'Quarter of Beef', label: 'Quarter of Beef'},
	{value: 'Reel', label: 'Reel'},
	{value: 'Roll', label: 'Roll'},
	{value: 'Sack', label: 'Sack'},
	{value: 'Sheet', label: 'Sheet'},
	{value: 'Side of Beef', label: 'Side of Beef'},
	{value: 'Skid', label: 'Skid'},
	{value: 'Tank', label: 'Tank'},
	{value: 'Tote Bin', label: 'Tote Bin'},
	{value: 'Tube', label: 'Tube'},
	{value: 'Unit', label: 'Unit'},
]
